/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class frmMatriculaAlumno extends javax.swing.JFrame {

     private JCheckBox[] casillas1;
     private JCheckBox[] casillas2;
    
    /**
     * Creates new form frmMatriculaAlumno
     */
    public frmMatriculaAlumno() {
        initComponents();
        casillas1 = new JCheckBox[] {
            chkProgramacion,
        chkBasesDeDatos,
        chkLenguajeDeMarcas,
        chkSistemasInformaticos,
        chkFOL
        };
         casillas2 = new JCheckBox[] {
            chkDesarrolloEntornoServidor, chkDesarrolloEntornoCliente, chkHorasDeLibreConfiguracion,
            chkDiseñoDeInterfacesWeb,chkEmpresaEmprendedora
        };
        activarCasillas(casillas1,false);
        activarCasillas(casillas2,false);

    }

  
    private void activarCasillas (JCheckBox[] casillas, boolean activar){
       
        for(JCheckBox i : casillas){
            i.setEnabled(activar);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSeleccionarCurso = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chkProgramacion = new javax.swing.JCheckBox();
        chkSistemasInformaticos = new javax.swing.JCheckBox();
        chkLenguajeDeMarcas = new javax.swing.JCheckBox();
        chkBasesDeDatos = new javax.swing.JCheckBox();
        chkFOL = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        chkDesarrolloEntornoServidor = new javax.swing.JCheckBox();
        chkDesarrolloEntornoCliente = new javax.swing.JCheckBox();
        chkDiseñoDeInterfacesWeb = new javax.swing.JCheckBox();
        chkHorasDeLibreConfiguracion = new javax.swing.JCheckBox();
        chkEmpresaEmprendedora = new javax.swing.JCheckBox();
        optPrimero = new javax.swing.JRadioButton();
        optSegundo = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkProgramacion.setText("Programación");

        chkSistemasInformaticos.setText("Sistemas Informáticos");

        chkLenguajeDeMarcas.setText("Lenguaje de marcas");
        chkLenguajeDeMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLenguajeDeMarcasActionPerformed(evt);
            }
        });

        chkBasesDeDatos.setText("Bases de datos");

        chkFOL.setText("FOL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkProgramacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkSistemasInformaticos, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(chkLenguajeDeMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBasesDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkFOL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkProgramacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSistemasInformaticos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkLenguajeDeMarcas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBasesDeDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFOL)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkDesarrolloEntornoServidor.setText("Desarrollo entorno servidor");

        chkDesarrolloEntornoCliente.setText("Desarrollo entorno cliente");

        chkDiseñoDeInterfacesWeb.setText("Diseño de interfaces web");

        chkHorasDeLibreConfiguracion.setText("Horas de libre configuración");

        chkEmpresaEmprendedora.setText("Empresa emprendedora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDesarrolloEntornoServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkDesarrolloEntornoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDiseñoDeInterfacesWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkHorasDeLibreConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkEmpresaEmprendedora, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkDesarrolloEntornoServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDesarrolloEntornoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDiseñoDeInterfacesWeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHorasDeLibreConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkEmpresaEmprendedora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grpSeleccionarCurso.add(optPrimero);
        optPrimero.setText("1ºDAW");
        optPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPrimeroActionPerformed(evt);
            }
        });

        grpSeleccionarCurso.add(optSegundo);
        optSegundo.setText("2ºDAW");
        optSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSegundoActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optSegundo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optSegundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkLenguajeDeMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLenguajeDeMarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLenguajeDeMarcasActionPerformed

    private void generarMatricula(JCheckBox[] casillas){
        try{
            PrintWriter p = new PrintWriter("matricula.txt");
            p.println("ASIGNATURAS DE TU MATRÍCULA");
            if(optPrimero.isSelected()){
                for(JCheckBox i : casillas){
                    if(i.isSelected()){
                        p.println(i.getText());
                    }
                }
            }
            
            
            p.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(
                    this,
                    "Se ha producido este error "+e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    private void marcarCasillas(JCheckBox[] casillas, boolean marcar){
        for(JCheckBox i : casillas){
            i.setSelected(marcar);
        }
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(optPrimero.isSelected()){
            generarMatricula(casillas1);
        }else if(optSegundo.isSelected()){
            generarMatricula(casillas2);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void optPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPrimeroActionPerformed
        activarCasillas(casillas1, true);
        activarCasillas(casillas2, false);
        marcarCasillas(casillas2, false);
        marcarCasillas(casillas1, true);
    }//GEN-LAST:event_optPrimeroActionPerformed

    private void optSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSegundoActionPerformed
        activarCasillas(casillas2, true);
        activarCasillas(casillas1, false);
        marcarCasillas(casillas2, true);
        marcarCasillas(casillas1, false);
    }//GEN-LAST:event_optSegundoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMatriculaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMatriculaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMatriculaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMatriculaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMatriculaAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JCheckBox chkBasesDeDatos;
    private javax.swing.JCheckBox chkDesarrolloEntornoCliente;
    private javax.swing.JCheckBox chkDesarrolloEntornoServidor;
    private javax.swing.JCheckBox chkDiseñoDeInterfacesWeb;
    private javax.swing.JCheckBox chkEmpresaEmprendedora;
    private javax.swing.JCheckBox chkFOL;
    private javax.swing.JCheckBox chkHorasDeLibreConfiguracion;
    private javax.swing.JCheckBox chkLenguajeDeMarcas;
    private javax.swing.JCheckBox chkProgramacion;
    private javax.swing.JCheckBox chkSistemasInformaticos;
    private javax.swing.ButtonGroup grpSeleccionarCurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton optPrimero;
    private javax.swing.JRadioButton optSegundo;
    // End of variables declaration//GEN-END:variables
}
