/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author CARLOS
 */
public class frmVentanaPrincipal extends javax.swing.JFrame {

    private int contador;
    /**
     * Creates new form frmVentanaPrincipal
     */
    public frmVentanaPrincipal() {
        initComponents();
        this.contador=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPulsar = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtFrase = new javax.swing.JTextField();
        btnToUpperCase = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSetColorBlue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPulsar.setText("Pulsa el botón");
        btnPulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulsarActionPerformed(evt);
            }
        });

        lblTexto.setText("El botón ha sido pulsado 0 veces");

        btnReset.setText("Resetear");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraseActionPerformed(evt);
            }
        });

        btnToUpperCase.setText("Pasar a mayúsculas");
        btnToUpperCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToUpperCaseActionPerformed(evt);
            }
        });

        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSetColorBlue.setText("Poner letras en azul");
        btnSetColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetColorBlueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPulsar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReset)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnToUpperCase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSetColorBlue)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPulsar)
                    .addComponent(lblTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToUpperCase)
                    .addComponent(btnDelete)
                    .addComponent(btnSetColorBlue))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPulsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulsarActionPerformed
        // TODO add your handling code here:
        contador++;
         this.lblTexto.setText("El botón ha sido pulsado "+contador+" veces");
    }//GEN-LAST:event_btnPulsarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        contador=0;
        this.actualizarTexto();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnToUpperCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToUpperCaseActionPerformed

        String boton = btnToUpperCase.getText();
        if(boton.equals("pasar a mayúsculas")){
            String texto = txtFrase.getText();
            texto = texto.toUpperCase();
            txtFrase.setText(texto);
            btnToUpperCase.setText("pasar a minúsculas");
        }else{
        String texto = txtFrase.getText();
        texto = texto.toLowerCase();
        txtFrase.setText(texto);
        btnToUpperCase.setText("pasar a minúsculas");
    }
        
        
    }//GEN-LAST:event_btnToUpperCaseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        txtFrase.setText(" ");
        txtFrase.setForeground(Color.red);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSetColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetColorBlueActionPerformed
        // TODO add your handling code here:
        txtFrase.setForeground(Color.BLUE);
    }//GEN-LAST:event_btnSetColorBlueActionPerformed

    private void txtFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraseActionPerformed
        
    }//GEN-LAST:event_txtFraseActionPerformed

    private void actualizarTexto(){
        this.lblTexto.setText("El botón ha sido pulsado "+contador+" veces");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPulsar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSetColorBlue;
    private javax.swing.JButton btnToUpperCase;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextField txtFrase;
    // End of variables declaration//GEN-END:variables
}
